spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ChiangRai/distributed_project
          search-paths: /rai/github_configuration_file/rai_spring_cloud_config
          basedir: spring_cloud_file_config/file
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: test
    password: test
#          username: ****
#          password: ****



eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/,http://127.0.0.1:8763/eureka/
server:
  port: 8099

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"


management:
  endpoints:
    web:
      exposure:
        include: "*"



