

#ribbon 服务内部之间的负载均衡      服务名.ribbon.NFLoadBalancerRuleClassName.负载均衡的模式
CLIENT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    
spring:
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest
    
server:
  port: 8088
env: 穷查理.芒格

girl:
  name: xiaoping12334x89tt  
  age: 111
