eureka:
  client:
    service-url:
         defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8763/eureka/
    register-with-eureka: false
    fetch-registry: false


server:
  enable-self-preservation: false


spring:
  application:
    name: eureka

#server:
#  port: 8761

